name: Readme

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/lib.rs'
      - 'src/README.md'
      - 'src/README.tpl'
jobs:
  readme:
    name: README
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install cargo-readme
        run: |
          cargo install cargo-readme

      - name: Run cargo-readme
        run: |
          make readme

      - name: Check that README is up-to-date
        run: |
          # If this step fails, this means you haven't ran 'make readme' to update the README
          # with cargo-readme (cargo install cargo-readme).
          git diff --name-only | grep '^README.md$' > /dev/null && exit 1 || echo 'Thanks for keeping our README up-to-date :)'
